import Header from '@/Components/Layout/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/Components/Layout/NavBar'
import Last from '@/Components/Layout/Last'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        
        <main className='px-32'>
        {children}
        </main>
        <NavBar/>
        <Last/>
        </body>
    </html>
  )
}
