/* eslint-diEnter yoursable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
   
    "Auth": {
        "region": " region",
        "userPoolId": "Enter your pool id",
        "userPoolWebClientId": "Enter your client ID"
    }
};


export default awsExports;