/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
   
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_U0ILfCWNv",
        "userPoolWebClientId": "5omg665s11mimgspe4c2m1tq2t"
    }
};


export default awsExports;