/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
   
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_njPu5jv1W",
        "userPoolWebClientId": "39ia7fnhc65r4goe12cg27lvsg"
    }
};


export default awsExports;