/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
   
    "Auth": {
        "region": "Enter your region",
        "userPoolId": "Enter your pool id",
        "userPoolWebClientId": "Enter your client id"
    }
};


export default awsExports;